name: Build Windows App
on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Build Windows Executable
        run: |
          flet build windows --product-name "cityglass" --verbose

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cityglass-Windows-App
          path: build/windows